const phone='923334105708';
const general='Hello FJ Production, I would like to know more about your skincare products.';
const wa=text=>`https://wa.me/${phone}?text=${encodeURIComponent(text)}`;
const storeKey='fj-production-products';
let products=JSON.parse(localStorage.getItem(storeKey)||'[]');
const el=s=>document.querySelector(s);
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function orderMessage(p,q=1){return `Hello FJ Production, I would like to order:\n\nProduct: ${p.name}\nPrice: Rs. ${Number(p.price).toLocaleString()}\nQuantity: ${q}\n\nPlease confirm my order.`}
function categoryOptions(){const cats=[...new Set(products.map(p=>p.category))];el('#categoryFilter').innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option>${escapeHTML(c)}</option>`).join('')}
function render(){const query=el('#search').value.toLowerCase(),cat=el('#categoryFilter').value,range=el('#priceFilter').value;const shown=products.filter(p=>{let price=+p.price;return (!query||p.name.toLowerCase().includes(query))&&(!cat||p.category===cat)&&(!range||(range==='under-1000'&&price<1000)||(range==='1000-3000'&&price>=1000&&price<=3000)||(range==='over-3000'&&price>3000))});el('#products').innerHTML=shown.map((p,i)=>`<article class="product-card"><div class="product-image"><img loading="lazy" src="${p.image}" alt="${escapeHTML(p.name)}"></div><div class="product-info"><span class="product-meta">${escapeHTML(p.category)}</span><h3 class="product-title">${escapeHTML(p.name)}</h3><p class="product-desc">${escapeHTML(p.description)}</p><strong class="price">Rs. ${Number(p.price).toLocaleString()}</strong><div class="card-actions"><button class="view" data-view="${p.id}">View Details →</button><a class="small-order" href="${wa(orderMessage(p))}" target="_blank" rel="noopener">Order on WhatsApp ↗</a></div></div></article>`).join('');el('#empty').style.display=shown.length?'none':'block';renderManager()}
function renderManager(){const list=el('#manageList');if(!list)return;list.innerHTML=products.length?'<p class="footer-title">CURRENT PRODUCTS</p>'+products.map(p=>`<div class="manage-item"><img src="${p.image}" alt=""><span><b>${escapeHTML(p.name)}</b><br>Rs. ${Number(p.price).toLocaleString()}</span><button data-delete="${p.id}">Remove</button></div>`).join(''):''}
function details(id){const p=products.find(x=>x.id===id);if(!p)return;el('#dialogContent').innerHTML=`<div class="detail"><div class="detail-image"><img src="${p.image}" alt="${escapeHTML(p.name)}"></div><div class="detail-copy"><span class="product-meta">${escapeHTML(p.category)}</span><h2>${escapeHTML(p.name)}</h2><strong class="price">Rs. ${Number(p.price).toLocaleString()}</strong><p>${escapeHTML(p.description)}</p><p class="product-meta">ORDER QUANTITY</p><div class="quantity"><label for="qty">Quantity</label><input id="qty" type="number" value="1" min="1"></div><a id="detailOrder" class="button dark" target="_blank" rel="noopener">Order on WhatsApp <span>↗</span></a></div></div>`;const update=()=>el('#detailOrder').href=wa(orderMessage(p,Math.max(1,+el('#qty').value||1)));el('#qty').oninput=update;update();el('#productDialog').showModal()}
document.querySelectorAll('[data-general-order]').forEach(a=>{a.href=wa(general);a.target='_blank';a.rel='noopener'});el('#year').textContent=new Date().getFullYear();
el('#search').oninput=render;el('#categoryFilter').onchange=render;el('#priceFilter').onchange=render;
document.addEventListener('click',e=>{let id=e.target.closest('[data-view]')?.dataset.view;if(id)details(id);let del=e.target.closest('[data-delete]')?.dataset.delete;if(del){products=products.filter(p=>p.id!==del);localStorage.setItem(storeKey,JSON.stringify(products));categoryOptions();render()}});
document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
el('.menu').onclick=()=>{const nav=el('nav'),open=nav.classList.toggle('open');el('.menu').setAttribute('aria-expanded',open)};document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>el('nav').classList.remove('open'));
el('#manage').onclick=()=>el('#managerDialog').showModal();el('#productForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target),file=d.get('image');const reader=new FileReader();reader.onload=()=>{products.push({id:crypto.randomUUID(),name:d.get('name').trim(),price:d.get('price'),category:d.get('category').trim(),description:d.get('description').trim(),image:reader.result});localStorage.setItem(storeKey,JSON.stringify(products));e.target.reset();categoryOptions();render()};reader.readAsDataURL(file)};
categoryOptions();render();